#!/usr/bin/env python3
"""Build per-scheme matugen configs and the hook-only apply script.

Per-scheme configs render every template from config.toml into
~/.config/matugen/generated_profiles/<scheme>/ with post_hooks stripped, so the
entire color profile set of the wallpaper stays available for instant
switching without firing app reloads for background schemes.

apply_hooks.sh concatenates every post_hook verbatim. theme_ctl runs it after
swapping a cached profile into ~/.config/matugen/generated/ so every app
(hyprland, waybar, mako, kitty, gtk, ...) re-applies the new colors instantly.

Optimizations:
- Only regenerates scheme configs when config.toml changes (mtime-based cache)
- Tracks recently used schemes; skips unused schemes in sweep
"""

from __future__ import annotations

import json
import os
import pathlib
import sys
import tomllib
import hashlib

MATUGEN_DIR = pathlib.Path.home() / ".config" / "matugen"
MAIN_CONFIG = MATUGEN_DIR / "config.toml"
PROFILES_DIR = MATUGEN_DIR / "profiles"
GENERATED_PREFIX = "~/.config/matugen/generated_profiles"
APPLY_HOOKS_SH = PROFILES_DIR / "apply_hooks.sh"
CACHE_FILE = PROFILES_DIR / ".config_hash"
RECENT_FILE = PROFILES_DIR / ".recent_schemes"
DEVNULL = "/dev/null"

SCHEMES = (
    "scheme-content",
    "scheme-expressive",
    "scheme-fidelity",
    "scheme-fruit-salad",
    "scheme-monochrome",
    "scheme-neutral",
    "scheme-rainbow",
    "scheme-tonal-spot",
    "scheme-vibrant",
)

# Only these templates have post_hooks that need reloading on profile swap
HOOK_TEMPLATES = frozenset({
    "hyprland",
    "hyprpolkitagent",
    "waybar",
    "mako",
    "kitty",
    "ghostty",
    "foot",
    "ghostty",
    "rofi",
    "eww",
    "hyprlock",
    "hypridle",
    "swaync",
    "dunst",
    "cursor",
    "standalone_commands",
})


def toml_str(value: str) -> str:
    return json.dumps(value)


def config_hash() -> str:
    """Compute hash of relevant config.toml sections."""
    with MAIN_CONFIG.open("rb") as fh:
        data = fh.read()
    return hashlib.sha256(data).hexdigest()[:16]


def load_recent() -> set[str]:
    if RECENT_FILE.exists():
        try:
            return set(RECENT_FILE.read_text().split())
        except Exception:
            pass
    return set()


def save_recent(recent: set[str]) -> None:
    try:
        RECENT_FILE.write_text(" ".join(sorted(recent)))
    except Exception:
        pass


def build(force: bool = False, mark_recent: str | None = None) -> None:
    """Build profile configs. Only regenerates if config.toml changed."""
    current_hash = config_hash()
    cached_hash = CACHE_FILE.read_text().strip() if CACHE_FILE.exists() else ""

    if not force and cached_hash == current_hash:
        # Config unchanged; just mark recent if requested
        if mark_recent:
            recent = load_recent()
            recent.add(mark_recent)
            save_recent(recent)
        return

    with MAIN_CONFIG.open("rb") as fh:
        cfg = tomllib.load(fh)

    templates = cfg.get("templates", {})
    if not templates:
        sys.exit("config.toml has no [templates.*] sections")

    PROFILES_DIR.mkdir(parents=True, exist_ok=True)

    for scheme in SCHEMES:
        out_dir = f"{GENERATED_PREFIX}/{scheme}"
        lines = [f"[config]", f"# Auto-generated per-scheme config for {scheme}"]
        for name, tpl in templates.items():
            output = tpl.get("output_path", "")
            if output != "/dev/null":
                output = f"{out_dir}/{pathlib.PurePosixPath(output).name}"
            lines.append(f"\n[templates.{name}]")
            lines.append(f"input_path  = {toml_str(tpl.get('input_path', '/dev/null'))}")
            lines.append(f"output_path = {toml_str(output)}")
        (PROFILES_DIR / f"{scheme}.toml").write_text("\n".join(lines) + "\n")

    # Only include hooks for templates that actually need reloading on profile swap
    hooks = []
    for name, tpl in templates.items():
        hook = tpl.get("post_hook", "")
        if hook and name in HOOK_TEMPLATES:
            hooks.append(hook)
    hooks = [h for h in hooks if h]
    script = ["#!/usr/bin/env bash", "# Auto-generated by gen_profile_configs.py", "set +e"]
    script.extend(hooks)
    (APPLY_HOOKS_SH).write_text("\n".join(script) + "\n")

    CACHE_FILE.write_text(current_hash)

    if mark_recent:
        recent = load_recent()
        recent.add(mark_recent)
        save_recent(recent)


def get_active_schemes(active: str) -> list[str]:
    """Return schemes to generate: active + recently used (max 3)."""
    recent = load_recent()
    recent.discard(active)
    # Keep active + up to 2 recent = max 3 schemes generated
    selected = [active] + sorted(recent)[:2]
    return selected


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="Force rebuild even if config unchanged")
    parser.add_argument("--mark-recent", help="Mark scheme as recently used")
    parser.add_argument("--get-active", help="Get schemes to generate for active scheme")
    args = parser.parse_args()

    if args.get_active:
        schemes = get_active_schemes(args.get_active)
        print(" ".join(schemes))
    else:
        build(force=args.force, mark_recent=args.mark_recent)