#!/usr/bin/env python3
"""Build per-scheme matugen configs and the hook-only apply script.

Per-scheme configs render every template from config.toml into
~/.config/matugen/generated_profiles/<scheme>/ with post_hooks stripped, so the
entire color profile set of the wallpaper stays available for instant
switching without firing app reloads for background schemes.

apply_hooks.sh concatenates every post_hook verbatim. theme_ctl runs it after
swapping a cached profile into ~/.config/matugen/generated/ so every app
(hyprland, waybar, mako, kitty, gtk, ...) re-applies the new colors instantly.
"""

from __future__ import annotations

import json
import pathlib
import sys
import tomllib

MATUGEN_DIR = pathlib.Path.home() / ".config" / "matugen"
MAIN_CONFIG = MATUGEN_DIR / "config.toml"
PROFILES_DIR = MATUGEN_DIR / "profiles"
GENERATED_PREFIX = "~/.config/matugen/generated_profiles"
APPLY_HOOKS_SH = PROFILES_DIR / "apply_hooks.sh"
DEVNULL = "/dev/null"

SCHEMES = (
    "scheme-content",
    "scheme-expressive",
    "scheme-fidelity",
    "scheme-fruit-salad",
    "scheme-monochrome",
    "scheme-neutral",
    "scheme-rainbow",
    "scheme-tonal-spot",
    "scheme-vibrant",
)


def toml_str(value: str) -> str:
    return json.dumps(value)


def build() -> None:
    with MAIN_CONFIG.open("rb") as fh:
        cfg = tomllib.load(fh)

    templates = cfg.get("templates", {})
    if not templates:
        sys.exit("config.toml has no [templates.*] sections")

    PROFILES_DIR.mkdir(parents=True, exist_ok=True)

    for scheme in SCHEMES:
        out_dir = f"{GENERATED_PREFIX}/{scheme}"
        lines = [f"[config]", f"# Auto-generated per-scheme config for {scheme}"]
        for name, tpl in templates.items():
            output = tpl.get("output_path", "")
            if output != DEVNULL:
                output = f"{out_dir}/{pathlib.PurePosixPath(output).name}"
            lines.append(f"\n[templates.{name}]")
            lines.append(f"input_path  = {toml_str(tpl.get('input_path', DEVNULL))}")
            lines.append(f"output_path = {toml_str(output)}")
        (PROFILES_DIR / f"{scheme}.toml").write_text("\n".join(lines) + "\n")

    hooks = [tpl.get("post_hook", "") for tpl in templates.values()]
    hooks = [h for h in hooks if h]
    script = ["#!/usr/bin/env bash", "# Auto-generated by gen_profile_configs.py", "set +e"]
    script.extend(hooks)
    (APPLY_HOOKS_SH).write_text("\n".join(script) + "\n")


if __name__ == "__main__":
    build()
